config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users, controllers: { registrations: 'users/registrations', sessions: 'users/sessions', invitations: 'users/invitations' }

  resources :user_preferred_emails, except: [:new, :show, :edit] do
    collection do
      post :import
    end
  end
  patch   '/pause/:id'                                => 'user_preferred_emails#pause',              as: :pause

  resources :user_notification_templates, only: [:index, :create, :update]

  get     '/settings'                                 => 'users#settings',                           as: :my_settings
  post    '/user_email_notification'                  => 'users#user_email_notification',            as: :user_email_notification
  post    '/update_user'                              => 'users#update_user',                        as: :update_user
  delete  '/delete_logo'                              => 'users#delete_logo',                        as: :delete_logo
  get     '/users/update'                             => 'users#update',                             as: :users_update
  post    '/users/update_profile'                     => 'users#update_profile',                     as: :users_update_profile
  get     '/get_states'                               => 'users#get_states',                         as: :get_states
  get     '/get_cities'                               => 'users#get_cities',                         as: :get_cities
  post    '/paypal_callback'                          => 'users#paypal_callback',                    as: :paypal_callback
  get     '/check_username_unique'                    => 'users#check_username_unique',              as: :check_username_unique
  get     '/check_current_username_unique'            => 'users#check_current_username_unique',      as: :check_current_username_unique
  get     '/check_email_unique'                       => 'users#check_email_unique',                 as: :check_email_unique
  get     '/check_current_email_unique'               => 'users#check_current_email_unique',         as: :check_current_email_unique
  
  # Users Management
  get     '/users_management'                         => 'users_management#index',                   as: :users_management
  get     '/users_management/add_manager'             => 'users_management#add_manager',             as: :add_manager
  post    '/users_management/create_manager'          => 'users_management#create_manager',          as: :create_manager
  get     '/users_management/:user_id/edit_manager'   => 'users_management#edit_manager',            as: :edit_manager
  put     '/users_management/:user_id/update_manager' => 'users_management#update_manager',          as: :update_manager
  put     '/users_management/:user_id/update_status'  => 'users_management#update_status',           as: :update_status
  delete  '/users_management/:user_id/delete_manager' => 'users_management#delete_manager',          as: :delete_manager

  resources :sites, except: [:show] do
    member do
      get    :get_site_items
      get    :new_site_item
      post   :save_site_item
      post   :duplicate_last_item
      get    :get_site_item_templates
      post   :add_item_from_template
    end
    collection do
      post   :add_site_from_template
      post   :duplicate_existing_site
    end
  end
  get     '/sites/:id/destroy'                        => 'sites#destroy_show',                       as: :site_destroy_show
  put     '/sites/:id/update_item/:site_item_id'      => 'sites#update_site_item',                   as: :site_update_site_item
  delete  '/sites/:id/delete_item/:site_item_id'      => 'sites#delete_site_item',                   as: :site_delete_site_item
  get     '/sites/:id/upload_file/:site_item_id'      => 'sites#upload_site_item_file',              as: :upload_site_item_file
  post    '/sites/:id/create_file/:site_item_id'      => 'sites#create_site_item_file',              as: :create_site_item_file
  get     '/sites/:id/see_more/:site_tab_id'          => 'sites#see_more',                           as: :site_items_see_more
  get     '/site_item_question/:id/compliant'         => 'sites#site_item_question_compliant',       as: :site_item_question_compliant
  post    '/sites/:id/check_tab_name_unique'          => 'sites#check_tab_name_unique',              as: :check_tab_name_unique
  
  # Site Item Invitations
  get     '/sites/:id/invitations/:site_tab_id'       => 'site_item_invitations#invitations',        as: :invitations_site
  post    '/sites/:id/send_invitations'               => 'site_item_invitations#send_invitations',   as: :send_invitations_site
  delete  '/sites/:id/delete_invitations'             => 'site_item_invitations#delete_invitations', as: :delete_invitations_site
  get     '/sites/:id/get_invitations'                => 'site_item_invitations#get_invitations',    as: :get_invitations_site
  post    '/sites/:id/save_invitation/:site_item_id'  => 'site_item_invitations#save_invitation',    as: :site_save_invitation
  post    '/invitation/:id/pause'                     => 'site_item_invitations#pause_invitation',   as: :site_pause_invitation
  delete  '/invitation/:id/delete'                    => 'site_item_invitations#delete_invitation',  as: :site_delete_invitation
  put     '/invitation/:id/update'                    => 'site_item_invitations#update_invitation',  as: :site_update_invitation
  
  # Site Item Documents
  get     '/sites/:id/documents/:site_item_id'        => 'site_item_documents#documents',            as: :site_documents
  post    '/sites/:id/document/:site_item_id'         => 'site_item_documents#create_document',      as: :create_document
  get     '/document/:id/current'                     => 'site_item_documents#current_document',     as: :current_document
  get     '/document/:id/approve'                     => 'site_item_documents#approve_document',     as: :approve_document
  get     '/document/:id/pending'                     => 'site_item_documents#pending_document',     as: :pending_document
  get     '/document/:id/archive'                     => 'site_item_documents#archive_document',     as: :archive_document
  get     '/document/:id/delete'                      => 'site_item_documents#delete_document',      as: :delete_document
  get     '/document/:id/reject'                      => 'site_item_documents#reject_document',      as: :reject_document
  post    '/document/:id/due_soon'                    => 'site_item_documents#due_soon',             as: :due_soon_document
  get     '/document/:id/feedback'                    => 'site_item_documents#feedback',             as: :feedback_document
  post    '/document/:id/feedback'                    => 'site_item_documents#save_feedback',        as: :save_feedback_document
  
  resources :item_templates, except: [:show, :new, :edit]
  get     '/item_templates/:id/destroy'               => 'item_templates#destroy_show',              as: :item_template_destroy_show
  
  resources :reports, except: [:show, :edit, :update]
  
  get     '/about_us'                                 => 'home#about_us',                            as: :about_us
  get     '/contact_us'                               => 'home#contact_us',                          as: :contact_us
  post    '/contact_us'                               => 'home#save_contact_us',                     as: :save_contact_us
  get     '/pricing'                                  => 'home#pricing',                             as: :pricing
  get     '/faq'                                      => 'home#faq',                                 as: :faq
  get     '/why_us'                                   => 'home#why_us',                              as: :why_us
  get     '/terms_and_conditions'                     => 'home#terms_and_conditions',                as: :terms_and_conditions
  get     '/privacy_policy'                           => 'home#privacy_policy',                      as: :privacy_policy
  get     '/news'                                     => 'home#news',                                as: :news
  get     '/news/:id'                                 => 'home#news_show',                           as: :news_show
  post    '/news/:id/comment'                         => 'home#create_comment',                      as: :create_comment
  get     '/comment/:id/reply'                        => 'home#new_reply',                           as: :new_reply
  post    '/comment/:id/reply'                        => 'home#create_reply',                        as: :create_reply
  # services
  get     '/services'                                 => 'home#services',                            as: :services
  get     '/service/:id'                              => 'home#service_show',                        as: :service_show
  # teams
  get     '/teams'                                    => 'home#teams',                               as: :teams
  get     '/team/:id'                                 => 'home#team_show',                           as: :team_show
  # Send inquiry
  get     '/inquiry'                                  => 'home#inquiry',                             as: :inquiry                 
  post    '/create_inquiry'                           => 'home#create_inquiry',                      as: :create_inquiry                 
  # features
  get     '/features'                                 => 'home#features',                            as: :features
  get     '/feature/:id'                              => 'home#feature_show',                        as: :feature_show
  # Create Newsletter
  post    '/create_newsletter'                        => 'home#create_newsletter',                   as: :create_newsletter
  
  # mount Ckeditor::Engine => '/ckeditor'
  get     '/404'                                      => 'errors#not_found'

app/models/site_item_invitation.rb
class SiteItemInvitation < ActiveRecord::Base
  ## Relations
  belongs_to :user
  belongs_to :site
  belongs_to :site_item
  
	## Validations
	validates :user_id, :site_id, :site_item_id, presence: true, numericality: { only_integer: true, greater_than_or_equal_to: 0 }
	validates :upload_access_email, presence: true
  
  ## Class Methods
	def self.get_site_item_invitations(user)
		self.where(pause: false, upload_access_email: user.email).order("id ASC")
	end
end

app/controllers/site_item_invitations_controller.rb
class SiteItemInvitationsController < ApplicationController
  ## Filters
  before_action :authenticate_user!
  before_action :get_site, only: [:invitations, :save_invitation, :send_invitations, :delete_invitations, :get_invitations]
  before_action :get_site_item_invitation, only: [:pause_invitation, :delete_invitation, :update_invitation]
  skip_before_action :get_static_page, except: [:invitations]
  
  def invitations
    @site_tabs = @site.site_tabs.eager_load(:site_items).order("site_tabs.id ASC, site_items.id ASC")
    @site_tab = @site_tabs.select {|site_tab| site_tab.id == params[:site_tab_id].to_i}.first rescue ""
  end
  
  def save_invitation
    @site_item = @site.site_items.eager_load(:site_item_invitations).order("site_item_invitations.id ASC").find(params[:site_item_id]) rescue ""
    @saved = false
    if @site_item.present?
      if @site_item.site_item_invitations.where(upload_access_email: site_item_invitation_params[:upload_access_email]).last.blank?
        site_item_invitation = @site_item.site_item_invitations.new(site_item_invitation_params)
        already_user = User.user_email(site_item_invitation.upload_access_email)
        if already_user.present?
          roles = already_user.roles.pluck(:name)
          if roles.include? "contractor"
            save_site_item_invitation(site_item_invitation)
          end
        else
          save_site_item_invitation(site_item_invitation)
        end
      end
    end
  end
  
  def save_site_item_invitation(site_item_invitation)
    if site_item_invitation.save
      @site_item_invitations = @site_item.site_item_invitations
      @saved = true
    end
  end
  
  def pause_invitation
    if @site_item_invitation.pause?
      @saved = @site_item_invitation.update(pause: false)
    else
      @saved = @site_item_invitation.update(pause: true)
    end
  end
  
  def delete_invitation
    @site_item_invitation_id = @site_item_invitation.id
    @destroy = @site_item_invitation.destroy
  end
  
  def update_invitation
    @saved = @site_item_invitation.update(site_item_invitation_params)
  end
  
  def send_invitations
    @site.site_items.eager_load(:site_item_invitations).each do |site_item|
      site_item_invitations = site_item.site_item_invitations
      site_item_invitations.each do |site_item_invitation|
        unless site_item_invitation.invitation_sent?
          already_user = User.user_email(site_item_invitation.upload_access_email)
          if already_user.present?
            roles = already_user.roles.pluck(:name)
            if roles.include? "contractor"
              begin   
                SiteMailer.document_invitation(site_item_invitation, site_item, @site, current_user).deliver_now
                SiteMailer.invitation_confirmation(site_item_invitation, site_item, @site, current_user).deliver_now
              rescue => e
                Rails.logger.info "SiteMailer - invitation_confirmation, document_invitation: #{e}"
              end
            end
          else
            user = User.invite!(email: site_item_invitation.upload_access_email) do |u|
              u.skip_invitation = true
              u.add_role :contractor
            end
            token = user.raw_invitation_token
            begin   
              SiteMailer.document_invitation(site_item_invitation, site_item, @site, current_user, token).deliver_now
              SiteMailer.invitation_confirmation(site_item_invitation, site_item, @site, current_user).deliver_now
            rescue => e
              Rails.logger.info "SiteMailer - invitation_confirmation, invitation_confirmation: #{e}"
            end
          end
          site_item_invitation.update(invitation_sent: true)
        end
      end
    end
  end
  
  def delete_invitations
    @site.site_items.eager_load(:site_item_invitations).each do |site_item|
      site_item_invitations = site_item.site_item_invitations
      site_item_invitations.destroy_all if site_item_invitations.present?
    end
  end
  
  def get_invitations
    @site_tab = @site.site_tabs.find(params[:site_tab_id]) rescue ""
    @site_items = @site_tab.site_items.where(site_id: @site.id).eager_load(:site_item_questions, :site_item_invitations).order("site_items.id ASC, site_item_questions.id ASC")
  end
  
  private
    def get_site
      @site = Site.get_site(params[:id])
      unless @site.present?
        redirect_to root_path
      end
    end
    
    def get_site_item_invitation
      @site_item_invitation = SiteItemInvitation.find(params[:id]) rescue ""
      unless @site_item_invitation.present?
        redirect_to root_path
      end
    end
    
    def site_item_invitation_params
      params.require(:site_item_invitation).permit(:user_id, :site_id, :upload_access_email, :access_expires, :access_expires_date, :comment)
    end
end

app/helpers/site_item_invitations_helper.rb
module SiteItemInvitationsHelper
  def item_invitation_access_expires
    @item_invitation_access_expires ||= ItemInvitationAccessExpire.order("id ASC")
  end
end

app/views/site_item_invitations/_invitations.html.erb
<div class="transparentBox">
  <div class="innerPopWhite">
    <div class="popbox">
      <div class="popHeader clearfix">
        <div class="popHd fl">Send an Invitation to Upload</div>
        <span class="closePop fr">X</span>
      </div>
      <div class="popdetails">
        <div class="itemTemRow sendInvit clearfix">
          <div class="addTemplateBox sendInvitLeft fl">
            <div class="siteBox">
              <div class="addsiteHd blurBg">Site</div>
              <div class="siteFormRow">
                <div class="boldText"><%= site.name %></div>
              </div>
              <div class="addsiteHd greenBg mt20">Select Tab</div>
              <div class="siteFormRow tabAdded">
                <%= select_tag :site_tab, options_from_collection_for_select(site_tabs, :id, :name, site_tab.try(:id)), include_blank: false, class: "popInput bigSelect" %>
              </div>
              <div class="smallPara">
                <p>By Providing Upload Access to an item you are allowing a third party to upload documents and material to that item.
                </p>
                <p>Once an email address is added
                  <span class="c0070c0">m<span class="c00a551">y</span>compliance<span class="c00a551">.me</span>
                  </span>
                  will automatically send a notification email to yourself and to the recipient detailing membership requirements including username, and temporary password as well as instructions as to how to upload to the item.
                </p>
              </div>
            </div>
          </div>
          <div id="site_items_invitation">
            <%= render partial: "site_items_invitation", locals: { site: site, site_tab: site_tab } %>
          </div>
          <div class="clearfix"></div>
          <div class="btnGrpRight sendInvtBtn clearfix">
            <%= link_to "Save Changes", send_invitations_site_path(site), method: :post, remote: true, class: "saveBtn mt0" %>
            <%= link_to "Delete All Upload Access", delete_invitations_site_path(site), method: :delete, remote: true, data: {confirm: "Are you sure?"}, class: "saveBtn uploadAccess mt0" %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

<script type="text/javascript">
  (function($){
    $(".scrollbox").mCustomScrollbar({
      axis:"x",
      theme:"light-3",
      advanced:{autoExpandHorizontalScroll:true}
    });
    if($(window).width() > 767){
      $(".scrollbarCustom").mCustomScrollbar({
        axis:"Y",
        theme:"light-2"
      });
    }
  })(jQuery);

  $(function () {
    $("#site_tab").change(function (e) {
      if ($("#site_tab").val().length > 0) {
        $.get("<%= get_invitations_site_path(site) %>", {site_tab_id: $("#site_tab").val()});
      }
    });
  });
</script>

app/views/site_item_invitations/_site_item_invitation.html.erb
<td id="site_item_<%= site_item.id %>" class="site_item">
  <%= form_for(site_item_invitation, url: site_save_invitation_path(site, site_item), method: :post, remote: true, html: {id: "site_save_invitation_form_#{site_item.id}"}) do |f| %>
    <%= f.hidden_field :user_id, value: current_user.id %>
    <%= f.hidden_field :site_id, value: site.id %>
    <div class="siteBox itemTemBox2">
      <div class="addsiteHd blurBg">Item <%= index %></div>
      <div class="siteFormRow tabAdded">
        <label class="siteLabel">Item Title</label>
        <input type="text" class="popInput boldText" placeholder="Item Title" value="<%= site_item.title %>">
      </div>
      <div class="siteFormRow tabAdded">
        <label class="siteLabel">Provide Upload Access to</label>
        <%= f.email_field :upload_access_email, value: "", placeholder: "Enter email address", required: true, class: "popInput" %>
      </div>
      <div class="siteFormRow tabAdded">
        <label class="siteLabel">Access Expires</label>
        <%= f.text_field :access_expires, value: "", placeholder: "dd/mm/yyyy", required: true, class: "popInput calInput", id: "site_item_invitation_access_expires_#{site_item.id}" %>
        <%#= f.select :access_expires, (item_invitation_access_expires.map {|access_expire| [access_expire.expires.titleize, access_expire.expires]}), { include_blank: false, prompt: "Select" }, required: true, class: "select" %>
      </div>
      <%= f.submit "OK", class: "EditokBtn abtn" %>
      <div class="clearfix"></div>
      <div id="access_already_provided_<%= site_item.id %>" class="siteFormRow clearfix mt30" >  
        <%= render partial: "site_item_invitations", locals: { site_item_invitations: site_item_invitations } %>
      </div>
    </div>
  <% end %>
</td>

<!-- validation -->
<script type="text/javascript">
  $(document).ready(function(){
    $('#site_item_invitation_access_expires_<%= site_item.id %>').datetimepicker({
      format: "DD/MM/YYYY"
    });
    
    $("#site_item_invitation_access_expires_<%= site_item.id %>").inputmask({
      mask: "1/2/y",
      placeholder: "dd/mm/yyyy",
      alias: "date"
    });
    
    $("#site_save_invitation_form_<%= site_item.id %>").validate({
      rules: {
        "site_item_invitation[upload_access_email]": {
          required: true,
          noSpace: true,
          email: true,
          maxlength: 255
        },
        "site_item_invitation[access_expires]": {
          required: true
        }
      },
      messages: {
        "site_item_invitation[upload_access_email]": {
          required: "Please enter your email address.",
          noSpace: "Please enter valid email address.",
          email: "Please enter valid Email Address.",
          maxlength: "Your Email must be of maximum {0} characters."
        },
        "site_item_invitation[access_expires]": {
          required: "Please select any one."
        }
      },
    });
  });
</script>

app/views/site_item_invitations/_site_item_invitations.html.erb
<% if site_item_invitations.present? %>
  <% if site_item_invitations.size > 1 %>
    <label class="siteLabel">Access Already Provided to:</label>
  <% end %>
  <div class="scrollbarCustom" style="height: 100px;">
    <% site_item_invitations.each do |site_item_invitation| %>
      <% unless site_item_invitation.new_record? %>
        <div id="site_item_invitation_<%= site_item_invitation.id %>" class="emailRow clearfix">
          <%= link_to "mailto:#{site_item_invitation.upload_access_email}" , class: "fl lighttBlClr EmailLinks ww-bw" do %>
            <%= site_item_invitation.upload_access_email %>
          <% end %>
          
          <%= link_to site_delete_invitation_path(site_item_invitation), id: "delete_invitation_#{site_item_invitation.id}", remote: true, method: :delete, data: {confirm: "Are you sure?"}, class: "cross fr" do %>
            <%= image_tag("cross1.png", alt: "", class: "pr5") %>
          <% end %>
          <%= link_to site_pause_invitation_path(site_item_invitation), id: "pause_invitation_#{site_item_invitation.id}", remote: true, method: :post, data: {confirm: "Are you sure?"}, class: "pause fr" do %>
            <% if site_item_invitation.pause? %>
              <%= image_tag("videoicon.png", alt: "", class: "op2") %>
            <% else %>
              <%= image_tag("pause.png", alt: "") %>
            <% end %>
          <% end %>
        </div>
      <% end %>
    <% end %>
  </div>
<% end %>

app/views/site_item_invitations/_site_items_invitation.html.erb
<% if site_tab.present? %>
  <% site_items = site_tab.site_items.where(site_id: site.id).eager_load(:site_item_questions, :site_item_invitations).order("site_items.id ASC, site_item_questions.id ASC, site_item_invitations.id ASC") %>
  <div class="itemTempRight sendInvitRight fr">
    <div class="scrollbox scrollbarCustomEdit clearfix">
      <table cellpadding="0" cellspacing="0" border="0">
        <tr>
          <% site_items.each.with_index(1) do |site_item, index| %>
            <%= render partial: "site_item_invitation", locals: { site: site, site_item: site_item, site_item_invitations: site_item.site_item_invitations, site_item_invitation: site_item.site_item_invitations.new, index: index } %>
          <% end %>
        <tr>
      </table>
    </div>
  </div>
<% end %>

app/views/site_item_invitations/delete_invitation.js.erb
<% if @destroy %>
	$("#site_item_invitation_<%= @site_item_invitation_id %>").remove();
<% else %>
	$("#error_messages").html("Not deleted");
<% end %>

// set_footer();
// $('html').scrollTop(0);

app/views/site_item_invitations/delete_invitations.js.erb
$("#container_content").html("<%= j(render partial: 'invitations', locals: { site: @site }) %>");
$('html').scrollTop(0);

(function($){
  $(".scrollbox").mCustomScrollbar({
    axis:"x",
    theme:"light-3",
    advanced:{autoExpandHorizontalScroll:true}
  });
  if($(window).width() > 767){
    $(".scrollbarCustom").mCustomScrollbar({
      axis:"Y",
      theme:"light-2"
    });
  }
})(jQuery);

app/views/site_item_invitations/get_invitations.js.erb
<% if @site_tab.present? %>
  $("#site_items_invitation").html("<%= j(render partial: 'site_items_invitation', locals: { site: @site, site_tab: @site_tab }) %>");
<% end %>

(function($){
  $(".scrollbox").mCustomScrollbar({
    axis:"x",
    theme:"light-3",
    advanced:{autoExpandHorizontalScroll:true}
  });
  if($(window).width() > 767){
    $(".scrollbarCustom").mCustomScrollbar({
      axis:"Y",
      theme:"light-2"
    });
  }
})(jQuery);

app/views/site_item_invitations/invitations.html.erb
<% content_for(:title) do %>
  Send an Invitation to Upload
<% end %>

<%= render partial: 'invitations', locals: { site: @site, site_tabs: @site_tabs, site_tab: @site_tab } %>

app/views/site_item_invitations/invitations.js.erb
$("#sendInvitation").html("<%= j(render partial: 'invitations', locals: { site: @site, site_tabs: @site_tabs, site_tab: @site_tab }) %>");
$("#sendInvitation").fadeIn(300);
$("body").addClass("hiddens");

$(".closePop").click(function(){								 
  $(".popOverlay").fadeOut(300);
  $("body").removeClass("hiddens");
});

(function($){
  $(".scrollbox").mCustomScrollbar({
    axis:"x",
    theme:"light-3",
    advanced:{autoExpandHorizontalScroll:true}
  });
  if($(window).width() > 767){
    $(".scrollbarCustom").mCustomScrollbar({
      axis:"Y",
      theme:"light-2"
    });
  }
})(jQuery);

// document.title = "Send an Invitation to Upload"
// if (history && history.pushState) {
// 	history.pushState(null, document.title, "<%#= invitations_site_path(@site) %>");
// 	$(window).bind("popstate", function(){
//     $.getScript(location.href);
//   });
// }

// set_footer();
// $('html').scrollTop(0);

app/views/site_item_invitations/pause_invitation.js.erb
<% if @saved %>
	<% if @site_item_invitation.pause? %>
		$("#pause_invitation_<%= @site_item_invitation.id %>").html("<%= j(image_tag('videoicon.png', alt: '', class: 'op2')) %>");
	<% else %>
		$("#pause_invitation_<%= @site_item_invitation.id %>").html("<%= j(image_tag('pause.png', alt: '')) %>");
	<% end %>
<% else %>
	$("#error_messages").html("Not paused");
<% end %>

// set_footer();
// $('html').scrollTop(0);

app/views/site_item_invitations/save_invitation.js.erb
<% if @saved %>
	$("#site_save_invitation_form_<%= @site_item.id %>")[0].reset();
	$("#access_already_provided_<%= @site_item.id %>").html("<%= j(render partial: 'site_item_invitations', locals: { site_item_invitations: @site_item_invitations }) %>");
<% else %>
	$("#error_messages").html("Not Created");
<% end %>

(function($){
	$(".scrollbox").mCustomScrollbar({
		axis:"x",
		theme:"light-3",
		advanced:{autoExpandHorizontalScroll:true}
	});
	if($(window).width() > 767){
		$(".scrollbarCustom").mCustomScrollbar({
			axis:"Y",
			theme:"light-2"
		});
	}
})(jQuery);

// set_footer();
// $('html').scrollTop(0);

app/views/site_item_invitations/send_invitations.js.erb
$(".popOverlay").fadeOut(300);
$("body").removeClass("hiddens");

// $('html').scrollTop(0);

app/views/site_item_invitations/update_invitation.js.erb
<% if @saved %>
<% else %>
	$("#error_messages").html("Not updated");
<% end %>

// set_footer();
// $('html').scrollTop(0);