config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users, controllers: { registrations: 'users/registrations', sessions: 'users/sessions', invitations: 'users/invitations' }

  resources :user_preferred_emails, except: [:new, :show, :edit] do
    collection do
      post :import
    end
  end
  patch   '/pause/:id'                                => 'user_preferred_emails#pause',              as: :pause

  resources :user_notification_templates, only: [:index, :create, :update]

  get     '/settings'                                 => 'users#settings',                           as: :my_settings
  post    '/user_email_notification'                  => 'users#user_email_notification',            as: :user_email_notification
  post    '/update_user'                              => 'users#update_user',                        as: :update_user
  delete  '/delete_logo'                              => 'users#delete_logo',                        as: :delete_logo
  get     '/users/update'                             => 'users#update',                             as: :users_update
  post    '/users/update_profile'                     => 'users#update_profile',                     as: :users_update_profile
  get     '/get_states'                               => 'users#get_states',                         as: :get_states
  get     '/get_cities'                               => 'users#get_cities',                         as: :get_cities
  post    '/paypal_callback'                          => 'users#paypal_callback',                    as: :paypal_callback
  get     '/check_username_unique'                    => 'users#check_username_unique',              as: :check_username_unique
  get     '/check_current_username_unique'            => 'users#check_current_username_unique',      as: :check_current_username_unique
  get     '/check_email_unique'                       => 'users#check_email_unique',                 as: :check_email_unique
  get     '/check_current_email_unique'               => 'users#check_current_email_unique',         as: :check_current_email_unique
  
  # Users Management
  get     '/users_management'                         => 'users_management#index',                   as: :users_management
  get     '/users_management/add_manager'             => 'users_management#add_manager',             as: :add_manager
  post    '/users_management/create_manager'          => 'users_management#create_manager',          as: :create_manager
  get     '/users_management/:user_id/edit_manager'   => 'users_management#edit_manager',            as: :edit_manager
  put     '/users_management/:user_id/update_manager' => 'users_management#update_manager',          as: :update_manager
  put     '/users_management/:user_id/update_status'  => 'users_management#update_status',           as: :update_status
  delete  '/users_management/:user_id/delete_manager' => 'users_management#delete_manager',          as: :delete_manager

  resources :sites, except: [:show] do
    member do
      get    :get_site_items
      get    :new_site_item
      post   :save_site_item
      post   :duplicate_last_item
      get    :get_site_item_templates
      post   :add_item_from_template
    end
    collection do
      post   :add_site_from_template
      post   :duplicate_existing_site
    end
  end
  get     '/sites/:id/destroy'                        => 'sites#destroy_show',                       as: :site_destroy_show
  put     '/sites/:id/update_item/:site_item_id'      => 'sites#update_site_item',                   as: :site_update_site_item
  delete  '/sites/:id/delete_item/:site_item_id'      => 'sites#delete_site_item',                   as: :site_delete_site_item
  get     '/sites/:id/upload_file/:site_item_id'      => 'sites#upload_site_item_file',              as: :upload_site_item_file
  post    '/sites/:id/create_file/:site_item_id'      => 'sites#create_site_item_file',              as: :create_site_item_file
  get     '/sites/:id/see_more/:site_tab_id'          => 'sites#see_more',                           as: :site_items_see_more
  get     '/site_item_question/:id/compliant'         => 'sites#site_item_question_compliant',       as: :site_item_question_compliant
  post    '/sites/:id/check_tab_name_unique'          => 'sites#check_tab_name_unique',              as: :check_tab_name_unique
  
  # Site Item Invitations
  get     '/sites/:id/invitations/:site_tab_id'       => 'site_item_invitations#invitations',        as: :invitations_site
  post    '/sites/:id/send_invitations'               => 'site_item_invitations#send_invitations',   as: :send_invitations_site
  delete  '/sites/:id/delete_invitations'             => 'site_item_invitations#delete_invitations', as: :delete_invitations_site
  get     '/sites/:id/get_invitations'                => 'site_item_invitations#get_invitations',    as: :get_invitations_site
  post    '/sites/:id/save_invitation/:site_item_id'  => 'site_item_invitations#save_invitation',    as: :site_save_invitation
  post    '/invitation/:id/pause'                     => 'site_item_invitations#pause_invitation',   as: :site_pause_invitation
  delete  '/invitation/:id/delete'                    => 'site_item_invitations#delete_invitation',  as: :site_delete_invitation
  put     '/invitation/:id/update'                    => 'site_item_invitations#update_invitation',  as: :site_update_invitation
  
  # Site Item Documents
  get     '/sites/:id/documents/:site_item_id'        => 'site_item_documents#documents',            as: :site_documents
  post    '/sites/:id/document/:site_item_id'         => 'site_item_documents#create_document',      as: :create_document
  get     '/document/:id/current'                     => 'site_item_documents#current_document',     as: :current_document
  get     '/document/:id/approve'                     => 'site_item_documents#approve_document',     as: :approve_document
  get     '/document/:id/pending'                     => 'site_item_documents#pending_document',     as: :pending_document
  get     '/document/:id/archive'                     => 'site_item_documents#archive_document',     as: :archive_document
  get     '/document/:id/delete'                      => 'site_item_documents#delete_document',      as: :delete_document
  get     '/document/:id/reject'                      => 'site_item_documents#reject_document',      as: :reject_document
  post    '/document/:id/due_soon'                    => 'site_item_documents#due_soon',             as: :due_soon_document
  get     '/document/:id/feedback'                    => 'site_item_documents#feedback',             as: :feedback_document
  post    '/document/:id/feedback'                    => 'site_item_documents#save_feedback',        as: :save_feedback_document
  
  resources :item_templates, except: [:show, :new, :edit]
  get     '/item_templates/:id/destroy'               => 'item_templates#destroy_show',              as: :item_template_destroy_show
  
  resources :reports, except: [:show, :edit, :update]
  
  get     '/about_us'                                 => 'home#about_us',                            as: :about_us
  get     '/contact_us'                               => 'home#contact_us',                          as: :contact_us
  post    '/contact_us'                               => 'home#save_contact_us',                     as: :save_contact_us
  get     '/pricing'                                  => 'home#pricing',                             as: :pricing
  get     '/faq'                                      => 'home#faq',                                 as: :faq
  get     '/why_us'                                   => 'home#why_us',                              as: :why_us
  get     '/terms_and_conditions'                     => 'home#terms_and_conditions',                as: :terms_and_conditions
  get     '/privacy_policy'                           => 'home#privacy_policy',                      as: :privacy_policy
  get     '/news'                                     => 'home#news',                                as: :news
  get     '/news/:id'                                 => 'home#news_show',                           as: :news_show
  post    '/news/:id/comment'                         => 'home#create_comment',                      as: :create_comment
  get     '/comment/:id/reply'                        => 'home#new_reply',                           as: :new_reply
  post    '/comment/:id/reply'                        => 'home#create_reply',                        as: :create_reply
  # services
  get     '/services'                                 => 'home#services',                            as: :services
  get     '/service/:id'                              => 'home#service_show',                        as: :service_show
  # teams
  get     '/teams'                                    => 'home#teams',                               as: :teams
  get     '/team/:id'                                 => 'home#team_show',                           as: :team_show
  # Send inquiry
  get     '/inquiry'                                  => 'home#inquiry',                             as: :inquiry                 
  post    '/create_inquiry'                           => 'home#create_inquiry',                      as: :create_inquiry                 
  # features
  get     '/features'                                 => 'home#features',                            as: :features
  get     '/feature/:id'                              => 'home#feature_show',                        as: :feature_show
  # Create Newsletter
  post    '/create_newsletter'                        => 'home#create_newsletter',                   as: :create_newsletter
  
  # mount Ckeditor::Engine => '/ckeditor'
  get     '/404'                                      => 'errors#not_found'

app/views/shared/_compliance_box.html.erb
<% if !current_role.include? "contractor" %>
  <div class="comBox">
    <div class="notComplent">
      <%= link_to "javascript:;" do %>
        Compliance Due <span><%= due_compliant_sites %></span>
      <% end %>
    </div>
    <div class="complenceDue">
      <%= link_to "javascript:;" do %>
        Not Compliant <span><%= not_compliant_sites %></span>
      <% end %>
    </div>
  </div>
<% end %>

app/views/shared/_dashboard_header.html.erb
<!--Start Header-->
<div class="dashHeader clearfix">
	<div class="logodash fl">
    <%= link_to root_path, remote: true do %>
      <%= image_tag("dashlogo.jpg", alt: "")%>
    <% end %>
  </div>
  <div class="dashHeaderRight fr">
    <div id="compliance_box">
      <%= render partial: "shared/compliance_box", locals: {not_compliant_sites: @not_compliant_sites, due_compliant_sites: @due_compliant_sites} %>
    </div>
    <span class="settingIcon">
      <%= image_tag("setting.png", alt: "", class: "dropmenuSetting")%>
     	<div class="settingBox helpDropDown dropDown">
        <%#= link_to "My Profile", "#" %>
        <%= link_to "My User Settings", my_settings_path, remote: true %>
        <%= link_to "Item Templates", item_templates_path, remote: true %>
        <%= link_to "Notification Templates", user_notification_templates_path, remote: true %>
        <%= link_to "Preferred Email List", user_preferred_emails_path, remote: true %>
        <% if current_user.has_role? :company %>
     		 <%= link_to "Employee/ Manager user management", users_management_path, remote: true %>
     		<% end %>
        <%= link_to "Log Out", destroy_user_session_path, method: :delete %>
      </div>
    </span>
    <div class="colliersImage"><%= image_tag("colliers.jpg", alt: "")%></div>
  </div>
</div>
<!--End Header-->

app/views/shared/_footer.html.erb
<!--Start Footer-->
<footer class="clearfix">
  <div class="container">
    <div class="footerBox">
      <h1 class="ftrHead wow fadeInUp">Quick Links<div class="plus">+</div></h1>
      <div class="ftrCon">
        <ul class="ftrLsit wow fadeInUp">
          <li><%= link_to "Home", root_path, remote: true %></li>
          <li><%= link_to "About My compliance", about_us_path, remote: true %></li>  
          <li><%= link_to "Blog", "javascript:;" %></li>
          <li><%= link_to "Contact", contact_us_path, remote: true %></li>
        </ul>
      </div>
    </div>
    <div class="footerBox">
      <h1 class="ftrHead wow fadeInUp">Recent Post<div class="plus">+</div></h1>
      <div class="ftrCon">
        <% @popular_news.each do |news|%>
        <ul class="ftrLsit wow fadeInUp">
          <li><%= link_to news.title,news_show_path(news), remote: true %></li>
        </ul>
        <% end %>
        <% if @latest_popular_news.present? %>
          <% @latest_popular_news.each do |news|%>
            <ul class="ftrLsit wow fadeInUp">
             <li><%= link_to news.title,news_show_path(news), remote: true %></li>
            </ul>
          <% end %>
        <% end %>
      </div>
    </div>


    <div class="footerBox">
      <h1 class="ftrHead wow fadeInUp">About Us<div class="plus">+</div></h1>
      <div class="ftrCon">
        <ul class="ftrLsit wow fadeInUp">
          <li><%= link_to "Lorem ipsum dolor sit amet, consectetuer", "javascript:;" %></li> 
          <li><%= link_to "adipiscing elit, sed diam nonummy nibh", "javascript:;" %></li> 
          <li><%= link_to "euismod tincidunt ut laoreet dolore magna", "javascript:;" %></li> 
          <li><%= link_to "aliquam erat volutpat.", "javascript:;" %></li>
          <li><%= link_to "euismod tincidunt ut laoreet dolore magna", "javascript:;" %></li> 
          <li><%= link_to "aliquam erat volutpat.", "javascript:;" %></li>
        </ul>
      </div>
    </div>
    <div class="footerBox">
      <h1 class="ftrHead wow fadeInUp">Newsletter Sign Up<div class="plus">+</div></h1>
      <div class="ftrCon">
        <p class="wow fadeInUp">Subscribe to our newletter to receive the latest updates from My compliance</p>
        <%= form_for(newsletter, url: create_newsletter_path(newsletter), method: :post, remote: true) do |f| %>
          <%= f.email_field :email, class: "inputComn", placeholder: "Email", required: true %><br>
          <%= f.submit "Subscribe",class: "subsBtn abtn" %>
        <% end %>
      </div>
    </div>
  </div>
</footer>
<!--End Footer-->

<!--Start CopyRight-->
<div class="copyRight clearfix">
  <div class="container">
    <div class="copyLeftBox wow fadeInUp fl">
      <ul class="social">
        <li><%= link_to "", "javascript:;", class: "facebook" %></li>
        <li><%= link_to "", "javascript:;", class: "twitter" %></a></li>
        <li><%= link_to "", "javascript:;", class: "linkedin" %></li>
        <li><%= link_to "", "javascript:;", class: "gmail" %></li>      
      </ul>
    </div>
    <div class="copyRightBox wow fadeInUp fr">
      <p>Mycompliance.com © <%= Time.now.year %>. All Rights Reserved.</p>
    </div>
  </div>
</div>
<!--End CopyRight-->

<% unless user_signed_in? %>
  <!--Start Login PopUp-->
  <div class="backBg" id="loginpopup">
    <div class="loginBox">
      <div class="loginCon">
        <div class="mainHeading visibility">Sign <strong>IN now!</strong></div>
        <div class="loginForm">
          <%= form_for(@new_user, url: user_session_path, html: {id: "login_popup"}) do |f| %>
            <label>User Name / Email Id</label>
            <%= f.text_field :login, autofocus: true, required: true, placeholder: "User Name / Email Id", class: "inputComn" %>
            <label>Password</label>
            <%= f.password_field :password, required: true, placeholder: "***********", class: "inputComn" %>
            <div class="cstmchkBox clearfix">
              <div class="checkboxLeft">
                <%= f.check_box :remember_me, class: "css-checkbox1", id: "checkBox3" %> 
                <label for="checkBox3" class="css-label1 radGroup1">Remember Me</label>
              </div>
              <div class="checkboxRight">
              <%= link_to new_user_password_path, class: "forgotPass", remote: true do %>
                : &nbsp;&nbsp;&nbsp;&nbsp;Forgot Password?
              <% end %>
              </div>
            </div>
            <div class="popUpsBtns">
              <%= f.submit "Login", class: "loginBtnPops abtn" %>
              <!-- <span class="accounts">Don't have an account? <a href="javascript:;" class="signUpBtn">Sign Up Now!</a></span> -->
              <span class="accounts">Don't have an account? <%= link_to "Sign Up Now!", new_user_registration_path, class: "popUpLink", remote: true %></span>
            </div>
          <% end %>
        </div>
      </div>
      <div class="freeTrial">
        <span><%= link_to "Sign Up", "javascript:;" %>for a <strong>30 day</strong> free trial</span>
      </div>
      <div class="closebtn"><text>X</text></div>
    </div>
  </div>
  <!--End Login PopUp-->
  
  <!--Start Signup PopUp-->
  <div class="backBg" id="signuppopup">
    <div class="loginBox">
      <div class="loginCon">
      <div class="mainHeading visibility">Sign <strong> Up now!</strong></div>
      <div class="loginForm">
        <label>Enter Username or Enter Email Address</label>
        <input type="text" class="inputComn" value="" name="" placeholder="XYZ">
        <label>Enter Password</label>
        <input type="password" class="inputComn" value="" name="" placeholder="***********">
        <div class="cstmchkBox clearfix">
          <div class="checkboxLeft">
            <input type="checkbox" name="smoking" class="css-checkbox1" id="checkBox4"> 
            <label for="checkBox4" class="css-label1 radGroup1">I agree  to mycomplaince  Term & Services</label>
          </div>
        </div>
        <div class="popUpsBtns">
          <%= link_to "Login", "javascript:;", class: "loginBtnPops" %>
          <span class="accounts">Already have an account? <%= link_to "Sign In Now!", "javascript:;",class: "popUpLink LoginPoPUp" %></span>
        </div>
      </div>	
      </div>
      <div class="freeTrial">
        <span><%= link_to "Pay Now!", "javascript:;" %></span>
      </div>
      <div class="closebtn closebtn2"><text>X</text></div>
    </div>
  </div>
  <!--End Signup PopUp-->
<% end %>

<div class="ajax-loading">
  <span>
    <p id="please_wait"><strong>Please wait..</strong></p>
    <p><i class="glyphicon glyphicon-refresh gly-spin" aria-hidden="true"></i></p>
  </span>
</div>

<!-- Validation -->
<script type="text/javascript">
  $(document).ready(function(){
    $("#new_newsletter").validate({
      errorPlacement: function(error, element) {
        error.insertAfter( element );
      },
      rules: {
        "newsletter[email]": {
          required: true,
          email: true,
          noSpace: true,
          maxlength: 255
        }
      },
      messages: {   
        "newsletter[email]": {
          required: "Please enter your Email Address.",
          email: "Please enter valid Email Address.",
          noSpace: "Please enter valid Email Address.",
          maxlength: "Your Email must be of maximum {0} characters."
        }
      },
    });
  });
</script>

<%= analytics_init if GoogleAnalytics.valid_tracker? %>

app/views/shared/_header.html.erb
<!--Start Header-->
<header>
  <div class="container clearfix">
    <!--Start Logo-->
    <div class="logo fl">
      <%= link_to root_path do %>
        <%= image_tag("logo.png", alt: "")%>
      <% end %>
    </div>
    <!--End Logo-->
    <!--Start MenuBar-->
    <% if user_signed_in? %>
      <div class="menuBar fr">
        <ul>
          <li class="active">
              <%= link_to "Sites", root_path, remote: true %>
          </li>
          <li>
            <% if user_permission("manage_item_template") %>
              <%= link_to "Item Templates", item_templates_path, remote: true %>
            <% else %>
              <%= link_to "Item Templates", item_templates_path, remote: true, class: "disable" %>
            <% end %>
          </li>
          <li>
            <% if user_permission("preferred_emails") %>
              <%= link_to "Preferred EL", user_preferred_emails_path, remote: true %>
            <% else %>
              <%= link_to "Preferred EL", user_preferred_emails_path, remote: true, class: "disable" %>
            <% end %>
          </li>
          <li>
            <% if user_permission("user_settings") %>
              <%= link_to "Settings", my_settings_path, remote: true %>
            <% else %>
              <%= link_to "Settings", my_settings_path, remote: true, class: "disable" %>
            <% end %>
          </li>
          <li><%= link_to "Employee UM", users_management_path, remote: true if current_role.include?("company") %></li>
          <li><%= link_to "News", news_path, remote: true %></li>
          <li><%= link_to "Teams", teams_path, remote: true %></li>
        </ul>
      </div>
      <%= link_to t('links.logout'), destroy_user_session_path, method: :delete, class: "loginBtn LoginPoPUp" %>
    <% else %>
      <div class="menuBar fr">
        <ul>
          <li class="active"><%= link_to "Home", root_path, remote: true %></li>
          <li><%= link_to "Plans", pricing_path%></li>
          <li><%= link_to "Why Us", why_us_path, remote: true %></li>
          <li><%= link_to "Instant ROI", "javascript:;", remote: true %></li>
          <li><%= link_to "Contact", contact_us_path, remote: true %></li>
          <li><%= link_to "Support", "javascript:;", remote: true %></li>
        </ul>
      </div>
      <%= link_to "Login", "javascript:;", class: "loginBtn LoginPoPUp" %>
    <% end %>
    <!--End MenuBar-->
    <!--Start MonileNav-->
    <%= link_to "javascript:;", class: "mobnav" do %>
      <i></i><i></i><i></i><i></i>
    <% end %>

    <!--End MonileNav-->
  </div>
</header>
<!--End Header-->
<!-- 
<% if user_signed_in? %>
  <%= t('links.signed_as', user: current_user.email) %>
  <%= link_to t('links.logout'), destroy_user_session_path, method: :delete, class: "signIn logout" %>
<% else %>
  <%= link_to t('links.sign_in'), new_user_session_path, class: "signIn" %> 
  <%#= link_to t('links.sign_up'), new_user_registration_path, class: "signIn" %><br>
  <% plans = Plan.all %>
  <table>
    <tr>
  	  <% plans.each do |plan|%>
  	   <td>Name::<%=plan.name %></td>
  	  <% end %>
    </tr>
    <tr>
  	  <% plans.each do |plan|%>
  	   <td>Price::<%= plan.price %></td>
  	  <% end %>
    </tr>
    <tr>
  	  <% plans.each do |plan|%>
  	   <td><%=link_to "Sign up",new_user_registration_path(plan_id: plan.id)%></td>
  	  <% end %>
    </tr>
  </table>
<% end %> -->