config/routes.rb
  devise_for :users, controllers: { registrations: 'users/registrations', sessions: 'users/sessions', invitations: 'users/invitations' }

  resources :user_preferred_emails, except: [:new, :show, :edit] do
    collection do
      post :import
    end
  end
  patch   '/pause/:id'                                => 'user_preferred_emails#pause',              as: :pause

  resources :user_notification_templates, only: [:index, :create, :update]

  get     '/settings'                                 => 'users#settings',                           as: :my_settings
  post    '/user_email_notification'                  => 'users#user_email_notification',            as: :user_email_notification
  post    '/update_user'                              => 'users#update_user',                        as: :update_user
  delete  '/delete_logo'                              => 'users#delete_logo',                        as: :delete_logo
  get     '/users/update'                             => 'users#update',                             as: :users_update
  post    '/users/update_profile'                     => 'users#update_profile',                     as: :users_update_profile
  get     '/get_states'                               => 'users#get_states',                         as: :get_states
  get     '/get_cities'                               => 'users#get_cities',                         as: :get_cities
  post    '/paypal_callback'                          => 'users#paypal_callback',                    as: :paypal_callback
  get     '/check_username_unique'                    => 'users#check_username_unique',              as: :check_username_unique
  get     '/check_current_username_unique'            => 'users#check_current_username_unique',      as: :check_current_username_unique
  get     '/check_email_unique'                       => 'users#check_email_unique',                 as: :check_email_unique
  get     '/check_current_email_unique'               => 'users#check_current_email_unique',         as: :check_current_email_unique
  
  # Users Management
  get     '/users_management'                         => 'users_management#index',                   as: :users_management
  get     '/users_management/add_manager'             => 'users_management#add_manager',             as: :add_manager
  post    '/users_management/create_manager'          => 'users_management#create_manager',          as: :create_manager
  get     '/users_management/:user_id/edit_manager'   => 'users_management#edit_manager',            as: :edit_manager
  put     '/users_management/:user_id/update_manager' => 'users_management#update_manager',          as: :update_manager
  put     '/users_management/:user_id/update_status'  => 'users_management#update_status',           as: :update_status
  delete  '/users_management/:user_id/delete_manager' => 'users_management#delete_manager',          as: :delete_manager

  resources :sites, except: [:show] do
    member do
      get    :get_site_items
      get    :new_site_item
      post   :save_site_item
      post   :duplicate_last_item
      get    :get_site_item_templates
      post   :add_item_from_template
    end
    collection do
      post   :add_site_from_template
      post   :duplicate_existing_site
    end
  end
  get     '/sites/:id/destroy'                        => 'sites#destroy_show',                       as: :site_destroy_show
  put     '/sites/:id/update_item/:site_item_id'      => 'sites#update_site_item',                   as: :site_update_site_item
  delete  '/sites/:id/delete_item/:site_item_id'      => 'sites#delete_site_item',                   as: :site_delete_site_item
  get     '/sites/:id/upload_file/:site_item_id'      => 'sites#upload_site_item_file',              as: :upload_site_item_file
  post    '/sites/:id/create_file/:site_item_id'      => 'sites#create_site_item_file',              as: :create_site_item_file
  get     '/sites/:id/see_more/:site_tab_id'          => 'sites#see_more',                           as: :site_items_see_more
  get     '/site_item_question/:id/compliant'         => 'sites#site_item_question_compliant',       as: :site_item_question_compliant
  post    '/sites/:id/check_tab_name_unique'          => 'sites#check_tab_name_unique',              as: :check_tab_name_unique
  
  # Site Item Invitations
  get     '/sites/:id/invitations/:site_tab_id'       => 'site_item_invitations#invitations',        as: :invitations_site
  post    '/sites/:id/send_invitations'               => 'site_item_invitations#send_invitations',   as: :send_invitations_site
  delete  '/sites/:id/delete_invitations'             => 'site_item_invitations#delete_invitations', as: :delete_invitations_site
  get     '/sites/:id/get_invitations'                => 'site_item_invitations#get_invitations',    as: :get_invitations_site
  post    '/sites/:id/save_invitation/:site_item_id'  => 'site_item_invitations#save_invitation',    as: :site_save_invitation
  post    '/invitation/:id/pause'                     => 'site_item_invitations#pause_invitation',   as: :site_pause_invitation
  delete  '/invitation/:id/delete'                    => 'site_item_invitations#delete_invitation',  as: :site_delete_invitation
  put     '/invitation/:id/update'                    => 'site_item_invitations#update_invitation',  as: :site_update_invitation
  
  # Site Item Documents
  get     '/sites/:id/documents/:site_item_id'        => 'site_item_documents#documents',            as: :site_documents
  post    '/sites/:id/document/:site_item_id'         => 'site_item_documents#create_document',      as: :create_document
  get     '/document/:id/current'                     => 'site_item_documents#current_document',     as: :current_document
  get     '/document/:id/approve'                     => 'site_item_documents#approve_document',     as: :approve_document
  get     '/document/:id/pending'                     => 'site_item_documents#pending_document',     as: :pending_document
  get     '/document/:id/archive'                     => 'site_item_documents#archive_document',     as: :archive_document
  get     '/document/:id/delete'                      => 'site_item_documents#delete_document',      as: :delete_document
  get     '/document/:id/reject'                      => 'site_item_documents#reject_document',      as: :reject_document
  post    '/document/:id/due_soon'                    => 'site_item_documents#due_soon',             as: :due_soon_document
  get     '/document/:id/feedback'                    => 'site_item_documents#feedback',             as: :feedback_document
  post    '/document/:id/feedback'                    => 'site_item_documents#save_feedback',        as: :save_feedback_document
  
  resources :item_templates, except: [:show, :new, :edit]
  get     '/item_templates/:id/destroy'               => 'item_templates#destroy_show',              as: :item_template_destroy_show
  
  resources :reports, except: [:show, :edit, :update]
  
  get     '/about_us'                                 => 'home#about_us',                            as: :about_us
  get     '/contact_us'                               => 'home#contact_us',                          as: :contact_us
  post    '/contact_us'                               => 'home#save_contact_us',                     as: :save_contact_us
  get     '/pricing'                                  => 'home#pricing',                             as: :pricing
  get     '/faq'                                      => 'home#faq',                                 as: :faq
  get     '/why_us'                                   => 'home#why_us',                              as: :why_us
  get     '/terms_and_conditions'                     => 'home#terms_and_conditions',                as: :terms_and_conditions
  get     '/privacy_policy'                           => 'home#privacy_policy',                      as: :privacy_policy
  get     '/news'                                     => 'home#news',                                as: :news
  get     '/news/:id'                                 => 'home#news_show',                           as: :news_show
  post    '/news/:id/comment'                         => 'home#create_comment',                      as: :create_comment
  get     '/comment/:id/reply'                        => 'home#new_reply',                           as: :new_reply
  post    '/comment/:id/reply'                        => 'home#create_reply',                        as: :create_reply
  # services
  get     '/services'                                 => 'home#services',                            as: :services
  get     '/service/:id'                              => 'home#service_show',                        as: :service_show
  # teams
  get     '/teams'                                    => 'home#teams',                               as: :teams
  get     '/team/:id'                                 => 'home#team_show',                           as: :team_show
  # Send inquiry
  get     '/inquiry'                                  => 'home#inquiry',                             as: :inquiry                 
  post    '/create_inquiry'                           => 'home#create_inquiry',                      as: :create_inquiry                 
  # features
  get     '/features'                                 => 'home#features',                            as: :features
  get     '/feature/:id'                              => 'home#feature_show',                        as: :feature_show
  # Create Newsletter
  post    '/create_newsletter'                        => 'home#create_newsletter',                   as: :create_newsletter
  
  # mount Ckeditor::Engine => '/ckeditor'
  get     '/404'                                      => 'errors#not_found'
  get     '/500'                                      => 'errors#internal_server_error'
  
  devise_scope :user do
    authenticated :user do
      root to: 'sites#index'
    end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  ## Filters
  skip_before_action :get_static_page, only: [:create_comment, :new_reply, :create_reply, :save_contact_us]
  before_action :get_news, only: [:news_show, :create_comment]
  before_action :news_type, only: [:news, :news_show]
  
  def index
    @banners = BannerImage.where(active: true).order("id ASC") rescue ""
    @services = Service.where(show_on_home: true).order("id ASC") rescue ""
    @teams = Team.where(show_on_home: true).order("id ASC") rescue ""
    @news = News.where(show_on_home: true).order("id ASC") rescue ""
    @testimonials = Testimonial.where(active: true).order("id ASC") rescue ""
  end

  def about_us
  end

  def pricing
  end

  def faq
  end

  def why_us
  end

  def terms_and_conditions
  end

  # news
  def news
    archive_date = Date.parse(params[:archive]) rescue ""
    if params[:search].present?
      @news = News.where("title ILIKE :search", search: "%#{params[:search]}%")
    elsif params[:archive].present? && archive_date.present?
      @news = News.where("created_at >= ? AND created_at <= ?", archive_date.to_date.beginning_of_month, archive_date.to_date.end_of_month)
    else
      @news = News.order("id DESC")
    end
  end

  def news_show
    @comments = @news.comments.hash_tree(limit_depth: 7)
    @comment = @news.comments.new 
  end

  # send inquiry
  def inquiry
    @inquiry = Inquiry.new
  end

  def create_newsletter
    @message = ""
    @newsletter = Newsletter.new(newsletter_params)
    @saved = @newsletter.save
    if @saved
      begin   
        AdminMailer.send_newsletter_email(@newsletter).deliver_now
      rescue => e
        Rails.logger.info "AdminMailer - send_newsletter_email: #{e}"
      end
    end
  end

  def create_inquiry
    @inquiry = Inquiry.new(inquiry_params)
    @saved = @inquiry.save
    if @saved
      begin   
        AdminMailer.send_inquiry_email(@inquiry).deliver_now
      rescue => e
        Rails.logger.info "AdminMailer - send_inquiry_email: #{e}"
      end
    end
    redirect_to :back
  end

  # features
  def features
    @features = Feature.order("id DESC")
  end

  def feature_show
    @feature = Feature.find(params[:id])
    @features = Feature.all_except(@feature) rescue ""
    if @feature.blank?
      redirect_to root_path
    end

  end

  # services
  def services
    @services = Service.order("id DESC")
  end

  def service_show
    @service = Service.find(params[:id]) rescue ""
    if @service.blank?
      redirect_to root_path
    end
  end

  # team
  def teams
    @teams = Team.order("id ASC")
  end

  def team_show
    @team = Team.find(params[:id]) rescue ""
    @teams = Team.all_except(@team) rescue ""
    if @team.blank?
      redirect_to root_path
    end
  end

  # comment
  def create_comment
    @comment = @news.comments.new(comment_params)
    @saved = @comment.save 
    news_type
  end

  # reply
  def new_reply
    @comment = Comment.find(params[:id]) rescue ""
  end

  def create_reply
    @comment = Comment.new(comment_params)
    @saved = @comment.save
    @comments = @comment.news.comments.hash_tree
  end

  # contact_us
  def contact_us
    @contact = ContactUs.new
  end

  def save_contact_us
    @message = ""
    @saved = false
    contact = ContactUs.new(contact_params)
    if contact.save
      begin   
        AdminMailer.contact_us(contact).deliver_now
      rescue => e
        Rails.logger.info "AdminMailer - contact_us: #{e}"
      end
      @saved = true
      @message = "We will get back to you soon."
    else
      @message = "Sorry please try again."
    end
  end

  def privacy_policy
  end

  def news_search
    @news = News.where("title like :search",{search: "%#{search}%"})
  end 

  private
    def get_news
      @news = News.find(params[:id]) rescue ""
      if @news.blank?
        redirect_to root_path
      end
    end

    def news_type
      @popular_news = News.joins(:comments).select('news.*, count(comments.id) as comment_count').group("news.id").order("comment_count DESC").first(3)
      if @popular_news.size <= 2
        @latest_popular_news = News.where.not(id: @popular_news.select{|n| n.id}.uniq).order("created_at DESC").first(3-@popular_news.size)
      end
      @archive = News.all.group_by {|u| u.created_at.beginning_of_month }.keys
      @latest_news = News.order("created_at DESC").first(3)
    end
    
    def contact_params
      params.require(:contact_us).permit(:name, :email, :contact_number, :message)
    end
    
    def comment_params
      params.require(:comment).permit(:news_id, :parent_id, :user_name, :email, :message)
    end

    def inquiry_params
      params.require(:inquiry).permit(:name, :email, :contact_number, :message)
    end

    def newsletter_params
      params.require(:newsletter).permit(:name, :email)
    end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/_contact_us.html.erb
<% content_for(:title) do %>
  Contact Us
<% end %>

<!--Start Why Banner-->
<div class="whyBanner contactbanner">
  <div class="container">
    <div class="whyBannerCaption contactCaption wow fadeInUp"><h1>Space For TAg Line<br> That You Can Trust</h1></div>
  </div>
</div>
<!--End Why Banner-->

<!--Start Breadcrumbs-->
<div class="breadcrumbs">
  <div class="container">
    <ul>
      <li>
        <%= link_to root_path, remote: true do %>
          Home <%= image_tag("rightSignarrow.png", alt: "")%>
        <% end %>
      </li>
      <li class="active"><%= link_to "Contact Us", "javascript:;" %></li>
    </ul>
  </div>
</div>
<!--End Breadcrumbs-->

<!--Start get in touch-->
<div class="getinTouch clearfix">
  <div class="container">
    <div class="touchLeft fl">
      <div class="mainHeading wow fadeInUp visibility">Get<strong>In Touch</strong></div>
      <p class="wow fadeInUp">Lorem ipsum consectetur adipiscing elit. Vestibulum nec odio ipsum. Suspendisse cursus malesuada facilisis. Nunc consectetur odio sed dolor tincidunt porttitor.
      </p>

      <%= form_for(@contact, url: contact_us_path(@contact), method: :post, remote: true)  do |f| %>
        <% if static_page.present? && static_page.contact_us.present? %>
          <%= static_page.contact_us.html_safe %>
          <% else %>
            <div class="getinTouchForm">
          <%= f.text_field :name, class: "inputComn", placeholder: "Name" %>
          <%= f.email_field :email, class: "inputComn", placeholder: "Email" %>
          <%= f.text_field :contact_number, class: "inputComn", placeholder: "Contact" %>
          <%= f.text_area :message, rows: "4", cols: "50", class: "inputComn", placeholder: "Message" %>
          <%=f.submit "Submit" ,class: "submtBtn abtn" %>
            </div>
        <% end %>
      <% end %>
    </div>
    <div class="touchRight wow fadeInUp fr">
      <div class="mainHeading wow fadeInUp visibility">office<strong>In</strong></div>
      <ul class="addressContactList">
        <li>
          <%= link_to "javascript:;" do %>
           <%= image_tag("phone.png", alt: "")%><text>+11 (0) 200 1111 001</text>
          <% end %>
        </li>
        <li>
          <%= link_to "javascript:;" do %>
           <%= image_tag("phone.png", alt: "")%><text>+11 (0) 200 1111 001</text>
          <% end %>
        </li>
        <li>
          <%= link_to "javascript:;" do %>
            <%= image_tag("support.png", alt: "")%><text>support@tmy-compliance.com</text>
          <% end %>
        </li>
        <li>
          <%= link_to "javascript:;" do %>
            <%= image_tag("place.png", alt: "")%><text>Ipsum Lorem, place nice, RD nice <br>Lorem, state pace <br>78666</text>
          <% end %>
        </li>
      </ul>
    </div>
  </div>
</div>
<!--End Welcome-->

<!--Start locationin Map-->
<div class="locationMap clearfix">
  <div class="container">
    <div class="mainHeading wow fadeInUp visibility">Location<strong>In Map</strong></div>
    <div class="mapViews">
      <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d12607.20594710062!2d144.92926922828806!3d-37.81811852521498!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x6ad65d674616d46f%3A0x5045675218cfdf0!2sDocklands+VIC+3008%2C+Australia!5e0!3m2!1sen!2sin!4v1470397790310" width="100%" height="365" frameborder="0" style="border:0" allowfullscreen></iframe>
    </div>
  </div>
</div>
<!--End locationin Map-->

<script type="text/javascript">
$(document).ready(function(){
  $("#new_contact_us").validate({
    errorPlacement: function(error, element) {
      error.insertAfter( element );
    },
    rules: {
      "contact_us[name]": {
        required: true,
        noSpace: true,
        maxlength: 125
      },
      "contact_us[email]": {
        required: true,
        email: true,
        noSpace: true,
        maxlength: 255
      },
      "contact_us[contact_number]": {
        required: true,
        phone: true,
        minlength: 8,
        maxlength: 15
      },
      "contact_us[message]": {
        required: true,
        noSpace: true,
        minlength: 4,
        maxlength: 65000
      }
    },
    messages: {
      "contact_us[name]": {
        required: "Please enter your Name.",
        noSpace: "Please enter valid Name.",
        maxlength: "Your Name must be of maximum 125 digits."
      },
      "contact_us[email]": {
        required: "Please enter your Email Address.",
        email: "Please enter valid Email Address.",
        noSpace: "Please enter valid Email Address.",
        maxlength: "Your Email must be of maximum 255 digits."

      },
      "contact_us[contact_number]": {
        required: "Please enter your Contact Number.",
        phone: "Please enter valid Contact Number.",
        minlength: "Your Contact Number must be of minimum 8 digits.",
        maxlength: "Your Contact Number must be of maximum 15 digits."
      },
      "contact_us[message]": {
        required: "Please enter your Message.",
        noSpace: "Please enter valid Message.",
        minlength: "Your Message must contain minimum 4 characters.",
        maxlength: "Your Message must be of maximum 65000 digits."
      }
    },
  });
});
</script>

app/views/home/_news_home_show.html.erb
<div class="tittleBox">
	<div class="date">
		<h1><%= news.created_at.in_time_zone.strftime("%B") %><br> <b><%= news.created_at.in_time_zone.strftime("%d") %></b></h1>
		<div class="message"><%= image_tag("Message.png", alt: "")%><b><%= news.comments.count %></b></div>
	</div>
	<div class="tittleCon">
		<%= image_tag(news.image.url, alt: "")%>
		<h1><%= news.title %></h1>
		<span>Posted by <%= link_to "John", "javascript:;" %></span>
		<p><%= news.description %></p>
		<%= link_to "Read more", news_show_path(news),remote: true, class: "rdMore" %>
	</div>
</div>

app/views/home/_pricing.html.erb
<% content_for(:title) do %>
  Pricing
<% end %>

<% if static_page.present? && static_page.pricing.present? %>
	<%= static_page.pricing.html_safe %>
<% else %>
  <% plans = Plan.all %>
  <table>
    <tr>
  	  <% plans.each do |plan|%>
  	   <td>Name::<%=plan.name %></td>
  	  <% end %>
    </tr>
    <tr>
  	  <% plans.each do |plan|%>
  	   <td>Price::<%= plan.price %></td>
  	  <% end %>
    </tr>
    <tr>
  	  <% plans.each do |plan|%>
        <td>
          <% unless user_signed_in? %>
            <%= link_to "Sign up",new_user_registration_path(plan_id: plan.id) %>
          <% end %>
        </td>
  	  <% end %>
    </tr>
  </table>
<% end %>

app/views/home/_privacy_policy.html.erb
<% content_for(:title) do %>
  Privacy Policy
<% end %>

<!--Start Privacy policy container-->
<% if static_page.present? && static_page.privacy_policy.present? %>
  <%= static_page.privacy_policy.html_safe %>
<% else %>
<% end %>
<!--End Privacy policy container-->

app/views/home/_team.html.erb
<div class="teamBoxMain">
  <div class="teamBox">
    <%= image_tag(team.image.url, alt: "")%>
    <div class="teamCon">
		  <%= link_to "#{team.name.html_safe}", team_show_path(team), remote: true %>
      <div class="borderImg"><%= image_tag("borderBottomLine.png", alt: "", class: "plusSign") %></div>
      <p><%= team.description.html_safe %></p>
    </div>
  </div>
  <%= link_to "READ MORE", team_show_path(team),remote: true,  class: "readMoreBtn" %>
</div>

app/views/home/_team_show.html.erb
<% content_for(:title) do %>
  <%= team.name %>
<% end %>

<!--Start Why Banner-->
<div class="whyBanner">
	<div class="container">
		<div class="whyBannerCaption wow fadeInUp"><h1>Space For TAg Line<br> That You Can Trust</h1></div>
	</div>
</div>
<!--End Why Banner-->
	
<!--Start Breadcrumbs-->
<div class="breadcrumbs">
	<div class="container">
		<ul>
			<li>
				<%= link_to root_path, remote: true do %>
      	Home <%= image_tag("rightSignarrow.png", alt: "")%>
      	<% end %>
			</li>
			<li class="active">
				<%= link_to teams_path, remote: true, class: "clr" do %>
      	Team <%= image_tag("rightSignarrow.png", alt: "")%>
      	<% end %>
			</li>
			<li class="active"><%= link_to "#{team.name}", remote: true %></li>
		</ul>
	</div>
</div>
<!--End Breadcrumbs-->
<!--Start Team Person-->	
<div class="teamPerson">
	<div class="container">
		<div class="teamPersonLeft fl">
			 <%= image_tag(team.image.url, alt: "", class: "wow fadeInUp") %>
			<h1 class="wow fadeInUp"><%= team.name %></h1>
			<span class="wow fadeInUp">Lorem ipsum consectetur adipiscing</span>
			<ul class="social socialNew">
				<li><%= link_to "", "#{team.facebook}" , class: "facebook"%></li>
				<li><%= link_to "", "#{team.twitter}" , class: "twitter"%></li>
				<li><%= link_to "", "#{team.linkedin}" , class: "linkedin"%></li>
				<li><%= link_to "", "#{team.gmail}" , class: "gmail"%></li>
			</ul>
		</div>
		<div class="teamPersonRight fr">
			<h1 class="wow fadeInUp"><%= team.name.html_safe %></h1>
			<p class="wow fadeInUp"><%= team.description.html_safe%></p>
			<h1 class="wow fadeInUp">LOrem heading</h1>
			<p class="wow fadeInUp">Lorem ipsum consectetur adipiscing elit. Vestibulum nec odio ipsum. Suspendisse cursus malesuada facilisis. Nunc consectetur odio sed dolor tincidunt porttitor. Suspendisse cursus malesuada facilisis. Nunc consectetur odio sed dolor Suspendisse cursus malesuada facilisis. tincidunt porttitor. Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat. Ut wisi enim ad minim veniam, quis nostrud exerc.</p>
			<h1 class="wow fadeInUp">LOrem heading</h1>
			<p class="wow fadeInUp">Lorem ipsum consectetur adipiscing elit. Vestibulum nec odio ipsum. Suspendisse cursus malesuada facilisis. Nunc consectetur odio sed dolor tincidunt porttitor. Suspendisse cursus malesuada facilisis. Nunc consectetur odio sed dolor Suspendisse cursus malesuada facilisis. tincidunt porttitor. Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat. Ut wisi enim ad minim veniam, quis nostrud exerc.</p>
		</div>
	</div>
</div>
<!--End Team Person-->
	
<!--Start Related Team-->
<div class="ourTeam relatedTeam">
	<div class="container">
		<div class="mainHeading wow fadeInUp visibility">Related<strong>Team</strong></div>
		<p class="headPara wow fadeInUp visibility">Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat.</p>
		<div class="teamMain clearfix wow fadeInUp visibility">
		<% teams.each do |team| %>
			<%= render partial: "team", locals: { team: team } %>
		<% end %>
		</div>
	</div>
</div>
<!--End Related Team-->

app/views/home/_terms_and_conditions.html.erb
<% content_for(:title) do %>
  Terms of Use
<% end %>

<!--Start Terms and Conditions container-->
<% if static_page.present? && static_page.terms_and_conditions.present? %>
  <%= static_page.terms_and_conditions.html_safe %>
<% else %>
<% end %>
<!--End Terms and Conditions container-->

app/views/home/feature_show.html.erb
<%= render partial: "feature_show", locals: { feature: @feature, features: @features } %>

app/views/home/features.js.erb
$("#container_content").html("<%= j(render partial: 'features', locals: { static_page: @static_page, features: @features }) %>");
document.title = "Features"
if (history && history.pushState) {
	history.pushState(null, document.title, "<%= features_path %>");
	$(window).bind("popstate", function(){
    $.getScript(location.href);
  });
}

set_footer();
$('html').scrollTop(0);

app/views/home/inquiry.html.erb
<%=render partial: "inquiry", locals: { inquiry: @inquiry }%>

app/views/home/inquiry.js.erb
$("#container_content").html("<%= j(render partial: 'inquiry', locals: { static_page: @static_page, inquiry: @inquiry }) %>");
document.title = " Send inquiry"
if (history && history.pushState) {
	history.pushState(null, document.title, "<%= inquiry_path %>");
	$(window).bind("popstate", function(){
    $.getScript(location.href);
  });
}

set_footer();
$('html').scrollTop(0);

app/views/home/pricing.html.erb
<%= render partial: 'pricing', locals: { static_page: @static_page} %>

app/views/home/privacy_policy.js.erb
$("#container_content").html("<%= j(render partial: 'privacy_policy', locals: { static_page: @static_page }) %>");
document.title = "Privacy Policy"
if (history && history.pushState) {
	history.pushState(null, document.title, "<%= privacy_policy_path %>");
	$(window).bind("popstate", function(){
    $.getScript(location.href);
  });
}

set_footer();
$('html').scrollTop(0);

app/views/home/teams.html.erb
<%= render partial: 'teams', locals: { static_page: @static_page, teams: @teams } %>