config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users, controllers: { registrations: 'users/registrations', sessions: 'users/sessions', invitations: 'users/invitations' }

  resources :user_preferred_emails, except: [:new, :show, :edit] do
    collection do
      post :import
    end
  end
  patch   '/pause/:id'                                => 'user_preferred_emails#pause',              as: :pause

  resources :user_notification_templates, only: [:index, :create, :update]

  get     '/settings'                                 => 'users#settings',                           as: :my_settings
  post    '/user_email_notification'                  => 'users#user_email_notification',            as: :user_email_notification
  post    '/update_user'                              => 'users#update_user',                        as: :update_user
  delete  '/delete_logo'                              => 'users#delete_logo',                        as: :delete_logo
  get     '/users/update'                             => 'users#update',                             as: :users_update
  post    '/users/update_profile'                     => 'users#update_profile',                     as: :users_update_profile
  get     '/get_states'                               => 'users#get_states',                         as: :get_states
  get     '/get_cities'                               => 'users#get_cities',                         as: :get_cities
  post    '/paypal_callback'                          => 'users#paypal_callback',                    as: :paypal_callback
  get     '/check_username_unique'                    => 'users#check_username_unique',              as: :check_username_unique
  get     '/check_current_username_unique'            => 'users#check_current_username_unique',      as: :check_current_username_unique
  get     '/check_email_unique'                       => 'users#check_email_unique',                 as: :check_email_unique
  get     '/check_current_email_unique'               => 'users#check_current_email_unique',         as: :check_current_email_unique
  
  # Users Management
  get     '/users_management'                         => 'users_management#index',                   as: :users_management
  get     '/users_management/add_manager'             => 'users_management#add_manager',             as: :add_manager
  post    '/users_management/create_manager'          => 'users_management#create_manager',          as: :create_manager
  get     '/users_management/:user_id/edit_manager'   => 'users_management#edit_manager',            as: :edit_manager
  put     '/users_management/:user_id/update_manager' => 'users_management#update_manager',          as: :update_manager
  put     '/users_management/:user_id/update_status'  => 'users_management#update_status',           as: :update_status
  delete  '/users_management/:user_id/delete_manager' => 'users_management#delete_manager',          as: :delete_manager

  resources :sites, except: [:show] do
    member do
      get    :get_site_items
      get    :new_site_item
      post   :save_site_item
      post   :duplicate_last_item
      get    :get_site_item_templates
      post   :add_item_from_template
    end
    collection do
      post   :add_site_from_template
      post   :duplicate_existing_site
    end
  end
  get     '/sites/:id/destroy'                        => 'sites#destroy_show',                       as: :site_destroy_show
  put     '/sites/:id/update_item/:site_item_id'      => 'sites#update_site_item',                   as: :site_update_site_item
  delete  '/sites/:id/delete_item/:site_item_id'      => 'sites#delete_site_item',                   as: :site_delete_site_item
  get     '/sites/:id/upload_file/:site_item_id'      => 'sites#upload_site_item_file',              as: :upload_site_item_file
  post    '/sites/:id/create_file/:site_item_id'      => 'sites#create_site_item_file',              as: :create_site_item_file
  get     '/sites/:id/see_more/:site_tab_id'          => 'sites#see_more',                           as: :site_items_see_more
  get     '/site_item_question/:id/compliant'         => 'sites#site_item_question_compliant',       as: :site_item_question_compliant
  post    '/sites/:id/check_tab_name_unique'          => 'sites#check_tab_name_unique',              as: :check_tab_name_unique
  
  # Site Item Invitations
  get     '/sites/:id/invitations/:site_tab_id'       => 'site_item_invitations#invitations',        as: :invitations_site
  post    '/sites/:id/send_invitations'               => 'site_item_invitations#send_invitations',   as: :send_invitations_site
  delete  '/sites/:id/delete_invitations'             => 'site_item_invitations#delete_invitations', as: :delete_invitations_site
  get     '/sites/:id/get_invitations'                => 'site_item_invitations#get_invitations',    as: :get_invitations_site
  post    '/sites/:id/save_invitation/:site_item_id'  => 'site_item_invitations#save_invitation',    as: :site_save_invitation
  post    '/invitation/:id/pause'                     => 'site_item_invitations#pause_invitation',   as: :site_pause_invitation
  delete  '/invitation/:id/delete'                    => 'site_item_invitations#delete_invitation',  as: :site_delete_invitation
  put     '/invitation/:id/update'                    => 'site_item_invitations#update_invitation',  as: :site_update_invitation
  
  # Site Item Documents
  get     '/sites/:id/documents/:site_item_id'        => 'site_item_documents#documents',            as: :site_documents
  post    '/sites/:id/document/:site_item_id'         => 'site_item_documents#create_document',      as: :create_document
  get     '/document/:id/current'                     => 'site_item_documents#current_document',     as: :current_document
  get     '/document/:id/approve'                     => 'site_item_documents#approve_document',     as: :approve_document
  get     '/document/:id/pending'                     => 'site_item_documents#pending_document',     as: :pending_document
  get     '/document/:id/archive'                     => 'site_item_documents#archive_document',     as: :archive_document
  get     '/document/:id/delete'                      => 'site_item_documents#delete_document',      as: :delete_document
  get     '/document/:id/reject'                      => 'site_item_documents#reject_document',      as: :reject_document
  post    '/document/:id/due_soon'                    => 'site_item_documents#due_soon',             as: :due_soon_document
  get     '/document/:id/feedback'                    => 'site_item_documents#feedback',             as: :feedback_document
  post    '/document/:id/feedback'                    => 'site_item_documents#save_feedback',        as: :save_feedback_document
  
  resources :item_templates, except: [:show, :new, :edit]
  get     '/item_templates/:id/destroy'               => 'item_templates#destroy_show',              as: :item_template_destroy_show
  
  resources :reports, except: [:show, :edit, :update]
  
  get     '/about_us'                                 => 'home#about_us',                            as: :about_us
  get     '/contact_us'                               => 'home#contact_us',                          as: :contact_us
  post    '/contact_us'                               => 'home#save_contact_us',                     as: :save_contact_us
  get     '/pricing'                                  => 'home#pricing',                             as: :pricing
  get     '/faq'                                      => 'home#faq',                                 as: :faq
  get     '/why_us'                                   => 'home#why_us',                              as: :why_us
  get     '/terms_and_conditions'                     => 'home#terms_and_conditions',                as: :terms_and_conditions
  get     '/privacy_policy'                           => 'home#privacy_policy',                      as: :privacy_policy
  get     '/news'                                     => 'home#news',                                as: :news
  get     '/news/:id'                                 => 'home#news_show',                           as: :news_show
  post    '/news/:id/comment'                         => 'home#create_comment',                      as: :create_comment
  get     '/comment/:id/reply'                        => 'home#new_reply',                           as: :new_reply
  post    '/comment/:id/reply'                        => 'home#create_reply',                        as: :create_reply
  # services
  get     '/services'                                 => 'home#services',                            as: :services
  get     '/service/:id'                              => 'home#service_show',                        as: :service_show
  # teams
  get     '/teams'                                    => 'home#teams',                               as: :teams
  get     '/team/:id'                                 => 'home#team_show',                           as: :team_show
  # Send inquiry
  get     '/inquiry'                                  => 'home#inquiry',                             as: :inquiry                 
  post    '/create_inquiry'                           => 'home#create_inquiry',                      as: :create_inquiry                 
  # features
  get     '/features'                                 => 'home#features',                            as: :features
  get     '/feature/:id'                              => 'home#feature_show',                        as: :feature_show
  # Create Newsletter
  post    '/create_newsletter'                        => 'home#create_newsletter',                   as: :create_newsletter
  
  # mount Ckeditor::Engine => '/ckeditor'
  get     '/404'                                      => 'errors#not_found'

app/controllers/users_management_controller.rb
class UsersManagementController < ApplicationController
	# Filters
	before_action :authenticate_user!, :check_user_role
	before_action :get_manager, except: [:index, :add_manager, :create_manager]

	def index
		get_managers
  end
	
	def add_manager
		@manager = User.new
	end
	
	def create_manager
		params[:user][:permissions] = params[:user][:permissions].reject!(&:empty?).join(',') if params[:user][:permissions].present?
		manager = current_user.managers.new(user_params)
		manager.skip_confirmation!
		@saved = manager.save
		if @saved
			manager.add_role :manager
			password = params[:user][:password] rescue ""
			begin    
				UserMailer.manager_created(current_user, manager, password).deliver_now
	    	UserMailer.manager_account(manager, password).deliver_now
  		rescue => e
    		Rails.logger.info "UserMailer - manager_created, manager_account: #{e}"
  		end
			get_managers
		end
	end
	
	def edit_manager
	end
		
	def update_manager
		params[:user][:permissions] = params[:user][:permissions].reject!(&:empty?).join(',') if params[:user][:permissions].present?
		password = params[:user][:password] rescue ""
		if password.present? && (password.length >= 8) && !@manager.valid_password?(password)
			@saved = @manager.update_with_password(user_params)
			password_updated = true
		else
			@saved = @manager.update_without_password(user_params)
			password_updated = false
		end
		if @saved
			begin    
				UserMailer.manager_updated(@manager, password, password_updated).deliver_now
  		rescue => e
    		Rails.logger.info "UserMailer - manager_updated: #{e}"
  		end
			get_managers
		end
	end
	
	def update_status
		if @manager.active?
			@saved = @manager.update(active: false)
		else
			@saved = @manager.update(active: true)
		end
	end
	
	def delete_manager
		@destroy = @manager.destroy
	end
	
	private
		def check_user_role
			unless current_user.has_role? :company
				redirect_to root_path
			end
		end
		
		def get_managers
			@managers = current_user.managers.order("id ASC")
		end
		
		def get_manager
			@manager = current_user.managers.find(params[:user_id]) rescue ""
			if @manager.blank?
				redirect_to root_path
			end
		end
		
		def user_params
			params.require(:user).permit(:first_name, :last_name, :landline_number, :job_title, :mobile_number, :email, :user_name, :password, :password_confirmation, :employee_id, :avatar, :permissions)
		end
end

app/helpers/users_management_helper.rb
module UsersManagementHelper
end

app/views/users_management/_index.html.erb
<div id="managers_list">
  <h2>List of Managers:</h2>
  <%= render partial: "managers", locals: { managers: managers } %>
</div>

<%= link_to "Add Manager", add_manager_path, remote: true %>

app/views/users_management/_manager.html.erb
<td><%= manager.email %></td>
<td><%= manager.user_name %></td>
<td><%= manager.full_name %></td>
<td><%= manager.landline_number %></td>
<td><%= manager.job_title %></td>
<td><%= manager.mobile_number %></td>
<td><%= manager.employee_id %></td>
<td><%= manager.active? ? "Active" : "Inactive" %></td>
<td><%= manager.current_sign_in_at.present? ? manager.current_sign_in_at.in_time_zone.strftime("%d-%b-%Y %I:%M:%S %p") : "" %></td>
<td><%=  manager.permissions %></td>
<td><%= link_to (manager.active? ? "Active" : "Inactive"), update_status_path(manager), method: :put, remote: true, data: { confirm: "Are you Sure?" } %> | <%= link_to "Edit", edit_manager_path(manager), remote: true %> | <%= link_to "Delete", delete_manager_path(manager), method: :delete, remote: true, data: { confirm: "Are you Sure?" } %></td>

app/views/users_management/_manager_edit_form.html.erb
<%= form_for(manager, url: update_manager_path, html: { method: :put, id: "manager_edit_form", remote: true }) do |f| %>
  <ul>
    <li>
    	<%= f.label "First Name"%>
      <%= f.text_field :first_name, placeholder: 'Enter First Name', required: true, class: "inputText" %>
    </li>
    <li>
    	<%= f.label "Last Name"%>
      <%= f.text_field :last_name, placeholder: 'Enter Last Name', required: true, class: "inputText" %>
    </li>
    <li>
    	<%= f.label "Phone Number"%>
      <%= f.text_field :landline_number, placeholder: 'Enter Phone Number', required: true, class: "inputText" %>
    </li>
    <li>
    	<%= f.label "Job Title"%>
      <%= f.text_field :job_title, placeholder: 'Enter Job Title', required: true, class: "inputText" %>
    </li>
    <li>
    	<%= f.label "Mobile Number"%>
      <%= f.text_field :mobile_number, placeholder: 'Enter Mobile Number', required: true, class: "inputText" %>
    </li>
    <li>
    	<%= f.label "Email ID"%>
      <%= f.email_field :email, placeholder: 'Enter Email ID', required: true, class: "inputText" %>
    </li>
    <li>
    	<%= f.label "UserName"%>
      <%= f.text_field :user_name, placeholder: 'Enter UserName', required: true, class: "inputText" %>
    </li>
    <div class="clearfix"></div>
    <li>
    	<%= f.label "Password"%>
      <%= f.password_field :password, autocomplete: "off", placeholder: 'Enter Password', class: "inputText mb5", required: false %>
    </li>
    <li>
    	<%= f.label "Re-enter password"%>
      <%= f.password_field :password_confirmation, autocomplete: "off", placeholder: 'Re-enter password', class: "inputText mb5", required: false %>
    </li>
    <li>
      <%= f.label "Permissions"%>
      <%= f.select :permissions, options_for_select([["My Account Settings", "my_account_settings"], ["Manage Documents","manage_documents"], ["Manage Templates","manage_templates"], ["Manage site","manage_site"],["Tabs","tabs"],["items","items"],["Notification","notification"],["Invitation","invitation"],["Add Site","add_site"],["Edit Site Information","edit_site_information"],["User Settings","user_settings"],["Manage Item Template","manage_item_template"],["Preferred Emails","preferred_emails"]],selected: manager.permissions), {}, multiple: true  %>  
    </li>
    <li>
      <%= f.label "Employee ID"%>
      <%= f.text_field :employee_id, placeholder: 'Enter Employee ID', required: false, class: "inputText" %>
    </li>
    <li>
    	<%= f.label "Image"%>
      <%= f.file_field :avatar, required: false, class: "inputText" %>
      <% if manager.avatar.present? %>
      	<%= image_tag(manager.avatar_url, class: 'image-preview-small', height: "100", width: "100") %>
      <% end %>
    </li>
    <div class="clearfix"></div>
  </ul>
  <div class="btn_center">
    <%= f.submit "Edit Manager", class: "btn_start piBtns" %>
  </div>
<% end %>


 <!-- validation -->

<script type="text/javascript">
  $(document).ready(function(){
    $("#manager_edit_form").validate({
      onkeyup: false,
      rules: {
        "user[first_name]": {
          required: true,
          noSpace: true,
          maxlength: 125
        },
        "user[last_name]": {
          required: true,
          noSpace: true,
          maxlength: 125
        },
        "user[landline_number]": {
          required: true,
          phone: true,
          minlength: 8,
          maxlength: 15
        },
        "user[job_title]": {
          required: true,
            maxlength: 125
        },
        "user[mobile_number]": {
          required: true,
          phone: true,
          minlength: 8,
          maxlength: 15
        },
        "user[email]": {
          required: true,
          noSpace: true,
          email: true,
          maxlength: 255,
          remote: {
            url: "/check_current_email_unique",
            type: "get",
            data: {
              email: function() {
                return "<%= manager.email %>";
              }
            }
          }
        },
        "user[user_name]": {
          required: true,
          noSpace: true,
          pattern: "^[a-zA-Z0-9_\.]*$",
          maxlength: 255,
          remote: {
            url: "/check_current_username_unique",
            type: "get",
            data: {
              username: function() {
                return "<%= manager.user_name %>";
              }
            }
          }
        },
        "user[employee_id]": {
          required: true,
          noSpace: true,
          maxlength: 125
        }
      },
      messages: {
        "user[first_name]": {
          required: "Please enter First Name.",
          noSpace: "Please enter valid First Name.",
          maxlength: "First Name must be of maximum {0} characters."
        },
        "user[last_name]": {
          required: "Please enter Last Name.",
          noSpace: "Please enter Last Name.",
          maxlength: "Last Name must be of maximum {0} characters."
        },
        "user[landline_number]": {
          required: "Please enter Phone Number.",
          phone: "Please enter valid Phone Number.",
          minlength: "Phone Number must be of minimum {0} digits.",
          maxlength: "Phone Number must be of maximum {0} digits."
        },
        "user[job_title]": {
          required: "Please enter Job Title.",
          noSpace: "Please enter valid Job Title.",
          maxlength: "Job Title must be of maximum {0} characters."
        },
        "user[mobile_number]": {
          required: "Please enter Mobile Number.",
          phone: "Please enter valid Mobile Number.",
          minlength: "Mobile Number must be of minimum {0} digits.",
          maxlength: "Mobile Number must be of maximum {0} digits."
        },
        "user[email]": {
          required: "Please enter Email Address.",
          noSpace: "Please enter valid Email Address.",
          email: "Please enter valid Email Address.",
          maxlength: "Email Address must be of maximum {0} characters.",
          remote: "This Email Address is taken."
        },
        "user[user_name]": {
          required: "Please enter User Name.",
          noSpace: "Please enter valid User Name.",
          pattern: "Please enter valid User Name.",
          maxlength: "User Name must be of maximum {0} characters.",
          remote: "This User Name is taken."
        },
        "user[password]": {
          required: "Please enter Password.",
          noSpace: "Please enter valid Password.",
          minlength: "Password must be of minimum {0} characters.",
          maxlength: "Password must be of maximum {0} characters."
        },
        "user[password_confirmation]": {
          required: "Please confirm Password.",
          noSpace: "Please enter valid Confirm Password.",
          minlength: "Confirm Password must be of minimum {0} characters.",
          maxlength: "Confirm Password must be of maximum {0} characters.",
          equalTo : "Confirm Password must be same as Password."
        },
        "user[employee_id]": {
          required: "Please enter Employee ID.",
          noSpace: "Please enter valid Employee ID.",
          maxlength: "Employee ID must be of maximum {0} characters."
        }
      },
      // highlight: function (element) {
      //   $(element).parent().removeClass("has-success").addClass("has-error");
      //   set_footer();
      // },
      // success: function (element) {
      //   $(element).parent().removeClass("has-error").addClass("has-success");
      //   $(element).removeClass("error");
      //   $(element).addClass("display-table margin-0");
      // }
    });
  });
</script>

app/views/users_management/_manager_form.html.erb
<%= form_for(manager, url: create_manager_path, html: { method: :post, id: "create_manager_form", remote: true }) do |f| %>
  <ul>
    <li>
    	<%= f.label "First Name"%>
      <%= f.text_field :first_name, placeholder: 'Enter First Name', required: true, class: "inputText" %>
    </li>
    <li>
    	<%= f.label "Last Name"%>
      <%= f.text_field :last_name, placeholder: 'Enter Last Name', required: true, class: "inputText" %>
    </li>
    <li>
    	<%= f.label "Phone Number"%>
      <%= f.text_field :landline_number, placeholder: 'Enter Phone Number', required: true, class: "inputText" %>
    </li>
    <li>
    	<%= f.label "Job Title"%>
      <%= f.text_field :job_title, placeholder: 'Enter Job Title', required: true, class: "inputText" %>
    </li>
    <li>
    	<%= f.label "Mobile Number"%>
      <%= f.text_field :mobile_number, placeholder: 'Enter Mobile Number', required: true, class: "inputText" %>
    </li>
    <li>
    	<%= f.label "Email ID"%>
      <%= f.email_field :email, placeholder: 'Enter Email ID', required: true, class: "inputText" %>
    </li>
    <li>
    	<%= f.label "UserName"%>
      <%= f.text_field :user_name, placeholder: 'Enter UserName', required: true, class: "inputText" %>
    </li>
    <div class="clearfix"></div>
    <li>
    	<%= f.label "Password"%>
      <%= f.password_field :password, autocomplete: "off", placeholder: 'Enter Password', class: "inputText mb5", required: true %>
    </li>
    <li>
    	<%= f.label "Re-enter password"%>
      <%= f.password_field :password_confirmation, autocomplete: "off", placeholder: 'Re-enter password', class: "inputText mb5", required: true %>
    </li>
    <li>
      <%= f.label "Permissions"%>
      <%= f.select :permissions, options_for_select([["My Account Settings", "my_account_settings"], ["Manage Documents","manage_documents"], ["Manage Templates","manage_templates"], ["Manage site","manage_site"],["Tabs","tabs"],["items","items"],["Notification","notification"],["Invitation","invitation"],["Add Site","add_site"],["Edit Site Information","edit_site_information"],["User Settings","user_settings"],["Manage Item Template","manage_item_template"],["Preferred Emails","preferred_emails"]],selected: manager.permissions), {}, multiple: true  %>  
    </li>
    <li>
    	<%= f.label "Employee ID"%>
      <%= f.text_field :employee_id, placeholder: 'Enter Employee ID', required: false, class: "inputText" %>
    </li>
    <li>
    	<%= f.label "Image"%>
      <%= f.file_field :avatar, required: false, class: "inputText" %>
    </li>
    <div class="clearfix"></div>
  </ul>
  <div class="btn_center">
    <%= f.submit "Add Manager", class: "btn_start piBtns" %>
  </div>
<% end %>

 <!-- validation -->

<script type="text/javascript">
  $(document).ready(function(){
    $("#create_manager_form").validate({
      onkeyup: false,
      rules: {
        "user[first_name]": {
          required: true,
          noSpace: true,
          maxlength: 125
        },
        "user[last_name]": {
          required: true,
          noSpace: true,
          maxlength: 125
        },
        "user[landline_number]": {
          required: true,
          phone: true,
          minlength: 8,
          maxlength: 15
        },
        "user[job_title]": {
          required: true,
          maxlength: 125
        },
        "user[mobile_number]": {
          required: true,
          phone: true,
          minlength: 8,
          maxlength: 15
        },
        "user[email]": {
          required: true,
          noSpace: true,
          email: true,
          maxlength: 255,
          remote: {
            url: "/check_email_unique",
            type: "get"
          }
        },
        "user[user_name]": {
          required: true,
          noSpace: true,
          pattern: "^[a-zA-Z0-9_\.]*$",
          maxlength: 255,
          remote: {
            url: "/check_username_unique",
            type: "get"
          }
        },
        "user[password]": {
          required: true,
          noSpace: true,
          minlength: 8,
          maxlength: 255
        },
        "user[password_confirmation]": {
          required: true,
          noSpace: true,
          minlength: 8,
          maxlength: 255,
          equalTo: "#user_password"
        },
        "user[employee_id]": {
          required: true,
          noSpace: true,
          maxlength: 125
        }
      },
      messages: {
        "user[first_name]": {
          required: "Please enter First Name.",
          noSpace: "Please enter valid First Name.",
          maxlength: "First Name must be of maximum {0} characters."
        },
        "user[last_name]": {
          required: "Please enter Last Name.",
          noSpace: "Please enter Last Name.",
          maxlength: "Last Name must be of maximum {0} characters."
        },
        "user[landline_number]": {
          required: "Please enter Phone Number.",
          phone: "Please enter valid Phone Number.",
          minlength: "Phone Number must be of minimum {0} digits.",
          maxlength: "Phone Number must be of maximum {0} digits."
        },
        "user[job_title]": {
          required: "Please enter Job Title.",
          noSpace: "Please enter valid Job Title.",
          maxlength: "Job Title must be of maximum {0} characters."
        },
        "user[mobile_number]": {
          required: "Please enter Mobile Number.",
          phone: "Please enter valid Mobile Number.",
          minlength: "Mobile Number must be of minimum {0} digits.",
          maxlength: "Mobile Number must be of maximum {0} digits."
        },
        "user[email]": {
          required: "Please enter Email Address.",
          noSpace: "Please enter valid Email Address.",
          email: "Please enter valid Email Address.",
          maxlength: "Email Address must be of maximum {0} characters.",
          remote: "This Email Address is taken."
        },
        "user[user_name]": {
          required: "Please enter User Name.",
          noSpace: "Please enter valid User Name.",
          pattern: "Please enter valid User Name.",
          maxlength: "User Name must be of maximum {0} characters.",
          remote: "This User Name is taken."
        },
        "user[password]": {
          required: "Please enter Password.",
          noSpace: "Please enter valid Password.",
          minlength: "Password must be of minimum {0} characters.",
          maxlength: "Password must be of maximum {0} characters."
        },
        "user[password_confirmation]": {
          required: "Please confirm Password.",
          noSpace: "Please enter valid Confirm Password.",
          minlength: "Confirm Password must be of minimum {0} characters.",
          maxlength: "Confirm Password must be of maximum {0} characters.",
          equalTo : "Confirm Password must be same as Password."
        },
        "user[employee_id]": {
          required: "Please enter Employee ID.",
          noSpace: "Please enter valid Employee ID.",
          maxlength: "Employee ID must be of maximum {0} characters."
        }
      },
      // highlight: function (element) {
      //   $(element).parent().removeClass("has-success").addClass("has-error");
      //   set_footer();
      // },
      // success: function (element) {
      //   $(element).parent().removeClass("has-error").addClass("has-success");
      //   $(element).removeClass("error");
      //   $(element).addClass("display-table margin-0");
      // }
    });
     });
</script>

app/views/users_management/_managers.html.erb
<table border="1">
  <tr>
    <th>Email</th>
    <th>UserName</th>
    <th>Name</th>
    <th>Phone Number</th>
    <th>Job Title</th>
    <th>Mobile Number</th>
    <th>Employee ID</th>
    <th>Account Status</th>
    <th>Last Login Date and Time</th>
    <th>Access Permissions</th>
    <th>Actions</th>
  </tr>
  <% managers.each do |manager| %>
    <tr id="manager_<%= manager.id %>">
      <%= render partial: "manager", locals: { manager: manager } %>
    </tr>
  <% end %>
</table>

app/views/users_management/add_manager.html.erb
<% content_for(:title) do %>
  Add Manager
<% end %>

<h2>Add a Manager</h2>
<%= render partial: "manager_form", locals: { manager: @manager } %>

app/views/users_management/add_manager.js.erb
$("#container_content").html("<%= j(render partial: 'manager_form', locals: { manager: @manager }) %>");
document.title = "Add Manager"
if (history && history.pushState) {
	history.pushState(null, document.title, "<%= add_manager_path %>");
	$(window).bind("popstate", function(){
    $.getScript(location.href);
  });
}

// set_footer();
$('html').scrollTop(0);

app/views/users_management/create_manager.js.erb
<% if @saved %>
	$("#container_content").html("<%= j(render partial: 'index', locals: { managers: @managers }) %>");
	document.title = "Users Management"
	if (history && history.pushState) {
		history.pushState(null, document.title, "<%= users_management_path %>");
		$(window).bind("popstate", function(){
	    $.getScript(location.href);
	  });
	}

	// set_footer();
	$('html').scrollTop(0);
<% else %>
<% end %>

app/views/users_management/delete_manager.js.erb
<% if @destroy %>
  $("#manager_<%= @manager.id %>").remove();
<% else %>
<% end %>

app/views/users_management/edit_manager.html.erb
<% content_for(:title) do %>
  Edit Manager
<% end %>

<h2>Edit a Manager</h2>
<%= render partial: "manager_edit_form", locals: { manager: @manager } %>

app/views/users_management/edit_manager.js.erb
$("#container_content").html("<%= j(render partial: 'manager_edit_form', locals: { manager: @manager }) %>");
document.title = "Edit Manager"
if (history && history.pushState) {
	history.pushState(null, document.title, "<%= edit_manager_path(@manager) %>");
	$(window).bind("popstate", function(){
    $.getScript(location.href);
  });
}

// set_footer();
$('html').scrollTop(0);

app/views/users_management/index.html.erb
<% content_for(:title) do %>
  Users Management
<% end %>

<%= render partial: "index", locals: { managers: @managers } %>

app/views/users_management/update_manager.js.erb
<% if @saved %>
	$("#container_content").html("<%= j(render partial: 'index', locals: { managers: @managers }) %>");
	document.title = "Users Management"
	if (history && history.pushState) {
		history.pushState(null, document.title, "<%= users_management_path %>");
		$(window).bind("popstate", function(){
	    $.getScript(location.href);
	  });
	}

	// set_footer();
	$('html').scrollTop(0);
<% else %>
<% end %>